name: Feature Request
description: Suggest a new feature or improvement.
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Thank you for suggesting an improvement! Please fill in the details below.

        Before opening a new feature request, please check
        [existing issues](https://github.com/llm-d/llm-d-infra/issues)
        to see if a similar request already exists.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        What problem does this feature solve? Describe the use case or pain point.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        Describe the solution you'd like. Be as specific as possible about
        expected behavior and user experience.
      placeholder: "Ideally, it would..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered.
    validations:
      required: false

  - type: dropdown
    id: contribution
    attributes:
      label: Willingness to Contribute
      description: Would you be willing to help implement this feature?
      options:
        - "Yes, I can submit a PR"
        - "Yes, with guidance"
        - "No, but I can help test"
        - "No"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, links, or references.
    validations:
      required: false
